
spring.application.name=genaisdk

spring.ai.google.genai.api-key=AIzaSyCkZJr01JvdAoV0X6SfU9CuiL1RhdTJErY

spring.ai.google.genai.chat.options.model=gemini-1.5-flash
spring.ai.google.genai.chat.options.model=gemini-1.5-flash-001
spring.ai.google.genai.chat.options.temperature=0.5
spring.ai.google.genai.chat.options.top-k=20
spring.ai.google.genai.chat.options.top-p=0.9


spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
